### PR TITLE
modified bouvet island phone code

### PR DESCRIPTION
**Pull request by ramyathay**
Changes made by Ramyatha

### CODE REVIEW

**Comment by mukeshsoni** [comment]
@ramyathay Can you please link to a source which mentions Bouvet Island country code as `55`? I googled and found that it was `47`.

**Comment by ramyathay** [comment]
@mukeshsoni I found these 2 sources - 
https://www.goldenchennai.com/isd-code/isd-code-for-bouvet-island/
http://www.country-dialing-codes.net/BVT/

**Comment by msonip** [comment]
@ramyathay It looks like `+55` is the dialing code of Brazil. Bouvet Island seems to be uninhabited - https://github.com/countries/countries/issues/315

There are conflicting values for Bouvet island in different places  https://www.distancelatlong.com/countrycode/of/bouvet-island

But the country code for Brazil consistently turns up as `55` everywhere - https://countrycode.org/brazil

**Comment by mukeshsoni** [comment]
@ramyathay It looks like `+55` is the dialing code of Brazil. Bouvet Island seems to be uninhabited - https://github.com/countries/countries/issues/315

There are conflicting values for Bouvet island in different places  https://www.distancelatlong.com/countrycode/of/bouvet-island

But the country code for Brazil consistently turns up as `55` everywhere - https://countrycode.org/brazil

**Pull request closed without merging**
